// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cboytwmvxoeijccfupjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNib3l0d212eG9laWpjY2Z1cGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTUwMDMsImV4cCI6MjA3NDI5MTAwM30.c9yJ2RSi6z9Znttq-A6QjX9CmY_UkECUDHbnrvbYGpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});